language: bash
sudo: required
services: docker
env:
    matrix:
        - ARCH=amd64
        - ARCH=arm32v7
deploy:
    provider: script
    script: ARCH=$ARCH make push-travis
    on:
        branch: master
